# Day 2: Rock Paper Scissors

<p><img src="rock-paper-scissors.svg.png"" alt="Markdown">.</p>

## Part One

The Elves begin to set up camp on the beach. To decide whose tent gets to be closest to the snack storage, a giant Rock Paper Scissors tournament is already in progress.

Rock Paper Scissors is a game between two players. Each game contains many rounds; in each round, the players each simultaneously choose one of Rock, Paper, or Scissors using a hand shape. Then, a winner for that round is selected: Rock defeats Scissors, Scissors defeats Paper, and Paper defeats Rock. If both players choose the same shape, the round instead ends in a draw.

Appreciative of your help yesterday, one Elf gives you an encrypted strategy guide (your puzzle input) that they say will be sure to help you win. "The first column is what your opponent is going to play: A for Rock, B for Paper, and C for Scissors. The second column--" Suddenly, the Elf is called away to help with someone's tent.

The second column, you reason, must be what you should play in response: X for Rock, Y for Paper, and Z for Scissors. Winning every time would be suspicious, so the responses must have been carefully chosen.

The winner of the whole tournament is the player with the highest score. Your total score is the sum of your scores for each round. The score for a single round is the score for the shape you selected (1 for Rock, 2 for Paper, and 3 for Scissors) plus the score for the outcome of the round (0 if you lost, 3 if the round was a draw, and 6 if you won).

Since you can't be sure if the Elf is trying to help you or trick you, you should calculate the score you would get if you were to follow the strategy guide.

For example, suppose you were given the following strategy guide:

|  |  |
|---|---|
| A | Y |
| B | X |
| C | Z |

This strategy guide predicts and recommends the following:

- In the first round, your opponent will choose Rock (A), and you should choose Paper (Y). This ends in a win for you with a score of 8 (2 because you chose Paper + 6 because you won).

- In the second round, your opponent will choose Paper (B), and you should choose Rock (X). This ends in a loss for you with a score of 1 (1 + 0).

 - The third round is a draw with both players choosing Scissors, giving you a score of 3 + 3 = 6.

In this example, if you were to follow the strategy guide, you would get a total score of 15 (8 + 1 + 6).

What would your total score be if everything goes exactly according to your strategy guide?

In [1]:
import numpy as np
import pandas as pd

In [2]:
rock_paper_scissors_df = pd.read_table('adventofcode.com_2022_day_2_input.txt', delimiter=' ', names=['oponent', 'response'])

In [3]:
rock_paper_scissors_df.head()

  oponent response
0       B        Z
1       A        Z
2       B        Z
3       C        Z
4       C        Z

In [4]:
# Data Dictionary

# Oponent Dictionary
oponent_dict = {
    'A':'Rock',
    'B':'Paper',
    'C':'Scissors'   
}
# Response Dictionary
response_dict = {
    'X':'Rock',
    'Y':'Paper',
    'Z':'Scissors'
}
# Point Dictionary
choice_dict = {
    'Rock':1,
    'Paper':2,
    'Scissors':3
}

In [5]:
rock_paper_scissors_df['oponent'] = rock_paper_scissors_df.oponent.map(oponent_dict)
rock_paper_scissors_df['response'] = rock_paper_scissors_df.response.map(response_dict)
rock_paper_scissors_df['choice_point'] = rock_paper_scissors_df.response.map(choice_dict)

In [6]:
rock_paper_scissors_df.sample(10)

       oponent  response  choice_point
945       Rock  Scissors             3
923       Rock  Scissors             3
1154      Rock  Scissors             3
1267      Rock      Rock             1
2382     Paper  Scissors             3
729       Rock      Rock             1
2110     Paper      Rock             1
894   Scissors      Rock             1
711   Scissors  Scissors             3
879      Paper  Scissors             3

In [7]:
match_conditions = [
    (rock_paper_scissors_df['oponent'] == 'Paper') & (rock_paper_scissors_df['response'] == 'Paper'),
    (rock_paper_scissors_df['oponent'] == 'Paper') & (rock_paper_scissors_df['response'] == 'Rock'),
    (rock_paper_scissors_df['oponent'] == 'Paper') & (rock_paper_scissors_df['response'] == 'Scissors'),
    (rock_paper_scissors_df['oponent'] == 'Rock') & (rock_paper_scissors_df['response'] == 'Paper'),
    (rock_paper_scissors_df['oponent'] == 'Rock') & (rock_paper_scissors_df['response'] == 'Rock'),
    (rock_paper_scissors_df['oponent'] == 'Rock') & (rock_paper_scissors_df['response'] == 'Scissors'),
    (rock_paper_scissors_df['oponent'] == 'Scissors') & (rock_paper_scissors_df['response'] == 'Paper'),
    (rock_paper_scissors_df['oponent'] == 'Scissors') & (rock_paper_scissors_df['response'] == 'Rock'),
    (rock_paper_scissors_df['oponent'] == 'Scissors') & (rock_paper_scissors_df['response'] == 'Scissors')   
]


match_values = [
    3,
    0,
    6,
    6,
    3,
    0,
    0,
    6,
    3
]

In [8]:
rock_paper_scissors_df['match_point'] = np.select(match_conditions, match_values, default=-9)
rock_paper_scissors_df['total_point'] = rock_paper_scissors_df.choice_point + rock_paper_scissors_df.match_point

In [9]:
rock_paper_scissors_df[
    np.logical_not(rock_paper_scissors_df.duplicated(keep='first'))
].style.set_caption('Match possible outcome')

In [10]:
rock_paper_scissors_df.total_point.sum()

10624

## Part Two

The Elf finishes helping with the tent and sneaks back over to you. "Anyway, the second column says how the round needs to end: X means you need to lose, Y means you need to end the round in a draw, and Z means you need to win. Good luck!"

The total score is still calculated in the same way, but now you need to figure out what shape to choose so the round ends as indicated. The example above now goes like this:

 - In the first round, your opponent will choose Rock (A), and you need the round to end in a draw (Y), so you also choose Rock. This gives you a score of 1 + 3 = 4.
 - In the second round, your opponent will choose Paper (B), and you choose Rock so you lose (X) with a score of 1 + 0 = 1.
 - In the third round, you will defeat your opponent's Scissors with Rock for a score of 1 + 6 = 7.

Now that you're correctly decrypting the ultra top secret strategy guide, you would get a total score of 12.

Following the Elf's instructions for the second column, what would your total score be if everything goes exactly according to your strategy guide?

In [11]:
import numpy as np
import pandas as pd

rock_paper_scissors_df = pd.read_table('adventofcode.com_2022_day_2_input.txt',
                                       delimiter=' ',
                                       names=['oponent', 'result'])

In [12]:
rock_paper_scissors_df.head()

  oponent result
0       B      Z
1       A      Z
2       B      Z
3       C      Z
4       C      Z

In [13]:
# Data Dictionary

# Oponent Dictionary
oponent_dict = {
    'A':'Rock',
    'B':'Paper',
    'C':'Scissors'   
}
# Result Dictionary
result_dict = {
    'X':'lose',
    'Y':'draw',
    'Z':'win'
}

In [14]:
rock_paper_scissors_df['oponent'] = rock_paper_scissors_df.oponent.map(oponent_dict)
rock_paper_scissors_df['result'] = rock_paper_scissors_df.result.map(result_dict)

In [15]:
rock_paper_scissors_df.sample(10)

       oponent result
1286  Scissors   draw
1328  Scissors   draw
1669      Rock   draw
1982     Paper    win
2306     Paper   draw
394       Rock    win
667   Scissors   draw
1646      Rock    win
446      Paper    win
295       Rock    win

In [16]:
response_contidions = [
    (rock_paper_scissors_df.oponent == 'Paper') & (rock_paper_scissors_df.result == 'win'),
    (rock_paper_scissors_df.oponent == 'Paper') & (rock_paper_scissors_df.result == 'draw'),
    (rock_paper_scissors_df.oponent == 'Paper') & (rock_paper_scissors_df.result == 'lose'),
    (rock_paper_scissors_df.oponent == 'Rock') & (rock_paper_scissors_df.result == 'win'),
    (rock_paper_scissors_df.oponent == 'Rock') & (rock_paper_scissors_df.result == 'draw'),
    (rock_paper_scissors_df.oponent == 'Rock') & (rock_paper_scissors_df.result == 'lose'),
    (rock_paper_scissors_df.oponent == 'Scissors') & (rock_paper_scissors_df.result == 'win'),
    (rock_paper_scissors_df.oponent == 'Scissors') & (rock_paper_scissors_df.result == 'draw'),
    (rock_paper_scissors_df.oponent == 'Scissors') & (rock_paper_scissors_df.result == 'lose')
]
response_values = [
    'Scissors',
    'Paper',
    'Rock',
    'Paper',
    'Rock',
    'Scissors',
    'Rock',
    'Scissors',
    'Paper'
]


# Choice Dictionary
choice_dict = {
    'Rock':1,
    'Paper':2,
    'Scissors':3
}

In [17]:
rock_paper_scissors_df['response'] = np.select(response_contidions, response_values, default=-9)
rock_paper_scissors_df['choice_point'] = rock_paper_scissors_df.response.map(choice_dict)

In [18]:
rock_paper_scissors_df[
    np.logical_not(rock_paper_scissors_df.duplicated(keep='first'))
].style.set_caption('Match possible outcome')

In [19]:
match_conditions = [
    (rock_paper_scissors_df.oponent == 'Paper') & (rock_paper_scissors_df.response == 'Paper'),
    (rock_paper_scissors_df.oponent == 'Paper') & (rock_paper_scissors_df.response == 'Rock'),
    (rock_paper_scissors_df.oponent == 'Paper') & (rock_paper_scissors_df.response == 'Scissors'),
    (rock_paper_scissors_df.oponent == 'Rock') & (rock_paper_scissors_df.response == 'Paper'),
    (rock_paper_scissors_df.oponent == 'Rock') & (rock_paper_scissors_df.response == 'Rock'),
    (rock_paper_scissors_df.oponent == 'Rock') & (rock_paper_scissors_df.response == 'Scissors'),
    (rock_paper_scissors_df.oponent == 'Scissors') & (rock_paper_scissors_df.response == 'Paper'),
    (rock_paper_scissors_df.oponent == 'Scissors') & (rock_paper_scissors_df.response == 'Rock'),
    (rock_paper_scissors_df.oponent == 'Scissors') & (rock_paper_scissors_df.response == 'Scissors')   
]
match_values = [
    3,
    0,
    6,
    6,
    3,
    0,
    0,
    6,
    3
]

In [20]:
rock_paper_scissors_df['match_point'] = np.select(match_conditions, match_values, default=-9)
rock_paper_scissors_df['total_point'] = rock_paper_scissors_df.choice_point + rock_paper_scissors_df.match_point

In [30]:
rock_paper_scissors_df[
    np.logical_not(rock_paper_scissors_df.duplicated(keep='first'))
].style.set_caption('####################### Match possible outcome #####################')

In [22]:
rock_paper_scissors_df.total_point.sum()

14060