 # Day 3: Rucksack Reorganization

## Part One

One Elf has the important job of loading all of the rucksacks with supplies for the jungle journey. Unfortunately, that Elf didn't quite follow the packing instructions, and so a few items now need to be rearranged.

Each rucksack has two large compartments. All items of a given type are meant to go into exactly one of the two compartments. The Elf that did the packing failed to follow this rule for exactly one item type per rucksack.

The Elves have made a list of all of the items currently in each rucksack (your puzzle input), but they need your help finding the errors. Every item type is identified by a single lowercase or uppercase letter (that is, a and A refer to different types of items).

The list of items for each rucksack is given as characters all on a single line. A given rucksack always has the same number of items in each of its two compartments, so the first half of the characters represent items in the first compartment, while the second half of the characters represent items in the second compartment.

For example, suppose you have the following list of contents from six rucksacks:

vJrwpWtwJgWrhcsFMMfFFhFp
jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
PmmdzqPrVvPwwTWBwg
wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
ttgJtRGJQctTZtZT
CrZsJsPPZsGzwwsLwLmpwMDw

 - The first rucksack contains the items vJrwpWtwJgWrhcsFMMfFFhFp, which means its first compartment contains the items vJrwpWtwJgWr, while the second compartment contains the items hcsFMMfFFhFp. The only item type that appears in both compartments is lowercase p.
 - The second rucksack's compartments contain jqHRNqRjqzjGDLGL and rsFMfFZSrLrFZsSL. The only item type that appears in both compartments is uppercase L.
 - The third rucksack's compartments contain PmmdzqPrV and vPwwTWBwg; the only common item type is uppercase P.
 - The fourth rucksack's compartments only share item type v.
 - The fifth rucksack's compartments only share item type t.
 - The sixth rucksack's compartments only share item type s

To help prioritize item rearrangement, every item type can be converted to a priority:

 - Lowercase item types a through z have priorities 1 through 26.
 - Uppercase item types A through Z have priorities 27 through 52.
 - In the above example, the priority of the item type that appears in both compartments of each rucksack is 16 (p), 38 (L), 42 (P), 22 (v), 20 (t), and 19 (s); the sum of these is 157.

Find the item type that appears in both compartments of each rucksack. What is the sum of the priorities of those item types?

### auxiliary functions

In [102]:
def verify_duplicated(word1:str, word2:str, word3:str=None):
    """
    A function that compares two string and returns a list of duplicated chars
    
    args:
        word1: first string to compare
        word2: second string to compare
        word:  Optional Third string to compare 
        
    Returns:
        a string that constains chars that apprears in the words at the same time
    """
    
    if word3 == None:
        for char in word1.strip():
            if char in word2.strip():
                return char
    else:
        for char in word1.strip():
            if char in word2.strip() and char in word3.strip():
                return char

In [103]:
import pandas as pd
import string


rucksack_df = pd.read_csv('adventofcode.com_2022_day_3_input.txt', names=['rucksack'])

In [104]:
rucksack_df.head()

                               rucksack
0                    wgqJtbJMqZVTwWPZZT
1              LHcTGHQhzrTzBsZFPHFZWFFs
2  RnLRClzGzRGLGLGCNRjTMjJfgmffSffMqNgp
3                    WPLgsfLmLgqZvZgSRR
4              RbwHdbDdQFFFMvvMjbhqhZZS

In [105]:
rucksack_df['compartment_1'] = rucksack_df.rucksack.apply(lambda x: x[:len(x)//2])

rucksack_df['compartment_2'] = rucksack_df.rucksack.apply(lambda x: x[len(x)//2:])

In [106]:
rucksack_df.head()

,rucksack,compartment_1,compartment_2
0,wgqJtbJMqZVTwWPZZT,wgqJtbJMq,ZVTwWPZZT
1,LHcTGHQhzrTzBsZFPHFZWFFs,LHcTGHQhzrTz,BsZFPHFZWFFs
2,RnLRClzGzRGLGLGCNRjTMjJfgmffSffMqNgp,RnLRClzGzRGLGLGCNR,jTMjJfgmffSffMqNgp
3,WPLgsfLmLgqZvZgSRR,WPLgsfLmL,gqZvZgSRR
4,RbwHdbDdQFFFMvvMjbhqhZZS,RbwHdbDdQFFF,MvvMjbhqhZZS

In [107]:
rucksack_df['duplicated_char'] = rucksack_df.apply(lambda x: verify_duplicated(x[1], x[2]), axis=1)

In [108]:
rucksack_df.sample(10)

,rucksack,compartment_1,compartment_2,duplicated_char
257,NCwwwQwllwnvgsvZzgzFZzBzjGGGMM,NCwwwQwllwnvgsv,ZzgzFZzBzjGGGMM,g
253,FQHWWCHwQmWmlqfCHSwJnsbNJnNsvttntBtb,FQHWWCHwQmWmlqfCHS,wJnsbNJnNsvttntBtb,w
85,DCDdvdGsVDVsflVdQSsfSwhRJlgppgpRpbWLgJbJpgbR,DCDdvdGsVDVsflVdQSsfSw,hRJlgppgpRpbWLgJbJpgbR,l
55,rqqGrrrqlnqqHqjNnVDSSSgQQffj,rqqGrrrqlnqqHq,jNnVDSSSgQQffj,n
125,rRHnLbhCzbbCHnHjMbzzjzFZmfQqWZQqvmhmfVZmqFBW,rRHnLbhCzbbCHnHjMbzzjz,FZmfQqWZQqvmhmfVZmqFBW,h
39,pSHShqgSMzVpphFnJMFMBtssdjRJ,pSHShqgSMzVpph,FnJMFMBtssdjRJ,M
49,mtPMbMqPMvqHHHDTTglBvsFshFFg,mtPMbMqPMvqHHH,DTTglBvsFshFFg,v
142,HphMMbbMdBMHbBhhgHMnhvwFFvtrlSNRNgcRllcvcc,HphMMbbMdBMHbBhhgHMnh,vwFFvtrlSNRNgcRllcvcc,g
2,RnLRClzGzRGLGLGCNRjTMjJfgmffSffMqNgp,RnLRClzGzRGLGLGCNR,jTMjJfgmffSffMqNgp,N
52,wdvwmhghhbtBMcLtwZ,wdvwmhghh,btBMcLtwZ,w

In [109]:
priorities_dict = {}

for index, char in enumerate(string.ascii_letters):
    priorities_dict[char] = index + 1

In [110]:
rucksack_df['priorities'] = rucksack_df.duplicated_char.map(priorities_dict)

In [111]:
rucksack_df.sample(10)

,rucksack,compartment_1,compartment_2,duplicated_char,priorities
64,dgMSPSMdQGclRRdF,dgMSPSMd,QGclRRdF,d,4
114,TRMrrGBLMLPtbssTGtBHwZmdQQbdNzzZZNZZdwjd,TRMrrGBLMLPtbssTGtBH,wZmdQQbdNzzZZNZZdwjd,b,2
95,fjCmDCGnfmTfFqrFnhqbFzqt,fjCmDCGnfmTf,FqrFnhqbFzqt,n,14
131,cpFCVNnVBHtbfFRtMRFf,cpFCVNnVBH,tbfFRtMRFf,F,32
212,jZNNNNjmjSPjFTJmGGzswwzHwHpBsbPblhhW,jZNNNNjmjSPjFTJmGG,zswwzHwHpBsbPblhhW,P,42
32,DzzwrtVFjLNnMTCTLCWW,DzzwrtVFjL,NnMTCTLCWW,L,38
76,FWcPQrrWqflzSWpRHZCZHRSt,FWcPQrrWqflz,SWpRHZCZHRSt,W,49
218,BGsGCnHmMlMwCfwT,BGsGCnHm,MlMwCfwT,C,29
283,NffHGrWzWWgDBfTRhChCnSCWcnjT,NffHGrWzWWgDBf,TRhChCnSCWcnjT,W,49
128,SPRsSwSvBsPRPsqzwSVqzmhVWtLWhTDNLlTDtLTWGpNMtDLt,SPRsSwSvBsPRPsqzwSVqzmhV,WtLWhTDNLlTDtLTWGpNMtDLt,h,8

In [112]:
answer_part_one = rucksack_df.priorities.sum()


print(f"The answer for the part one is: {answer_part_one}")

The answer for the part one is: 7727

## Part Two

As you finish identifying the misplaced items, the Elves come to you with another issue.

For safety, the Elves are divided into groups of three. Every Elf carries a badge that identifies their group. For efficiency, within each group of three Elves, the badge is the only item type carried by all three Elves. That is, if a group's badge is item type B, then all three Elves will have item type B somewhere in their rucksack, and at most two of the Elves will be carrying any other item type.

The problem is that someone forgot to put this year's updated authenticity sticker on the badges. All of the badges need to be pulled out of the rucksacks so the new authenticity stickers can be attached.

Additionally, nobody wrote down which item type corresponds to each group's badges. The only way to tell which item type is the right one is by finding the one item type that is common between all three Elves in each group.

Every set of three lines in your list corresponds to a single group, but each group can have a different badge item type. So, in the above example, the first group's rucksacks are the first three lines:

vJrwpWtwJgWrhcsFMMfFFhFp
jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
PmmdzqPrVvPwwTWBwg

And the second group's rucksacks are the next three lines:

wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
ttgJtRGJQctTZtZT
CrZsJsPPZsGzwwsLwLmpwMDw

In the first group, the only item type that appears in all three rucksacks is lowercase r; this must be their badges. In the second group, their badge item type must be Z.

Priorities for these items must still be found to organize the sticker attachment efforts: here, they are 18 (r) for the first group and 52 (Z) for the second group. The sum of these is 70.

Find the item type that corresponds to the badges of each three-Elf group. What is the sum of the priorities of those item types?

In [113]:
rucksack_df

,rucksack,compartment_1,compartment_2,duplicated_char,priorities
0,wgqJtbJMqZVTwWPZZT,wgqJtbJMq,ZVTwWPZZT,w,23
1,LHcTGHQhzrTzBsZFPHFZWFFs,LHcTGHQhzrTz,BsZFPHFZWFFs,H,34
2,RnLRClzGzRGLGLGCNRjTMjJfgmffSffMqNgp,RnLRClzGzRGLGLGCNR,jTMjJfgmffSffMqNgp,N,40
3,WPLgsfLmLgqZvZgSRR,WPLgsfLmL,gqZvZgSRR,g,7
4,RbwHdbDdQFFFMvvMjbhqhZZS,RbwHdbDdQFFF,MvvMjbhqhZZS,b,2
...,...,...,...,...,...
295,qvNnvWnvWDvSvqNtWSLWStqbcJBQwQJwQZHLBZbcmJbblb,qvNnvWnvWDvSvqNtWSLWStq,bcJBQwQJwQZHLBZbcmJbblb,L,38
296,DMtvqSvvDtntCRfwzGCgdzzFjG,DMtvqSvvDtntC,RfwzGCgdzzFjG,C,29
297,TfdZgtmfDgqgvlLFFsFHvcvZ,TfdZgtmfDgqg,vlLFFsFHvcvZ,Z,52
298,pphWQMVjQVVBWWjRlHlHnlcLDDhcnF,pphWQMVjQVVBWWj,RlHlHnlcLDDhcnF,h,8
299,JQwwWVPBwMJpJwpWwGBWNzrDzSSzfgTPqTSTTtSPgt,JQwwWVPBwMJpJwpWwGBWN,zrDzSSzfgTPqTSTTtSPgt,P,42

In [114]:
group_rucksack_lst = []
temp_lst = []
for row in  rucksack_df.rucksack:
    temp_lst.append(row)
    
    if len(temp_lst) == 3:
        group_rucksack_lst.append(temp_lst)
        temp_lst = []

In [115]:
group_rucksack_df = pd.DataFrame(group_rucksack_lst, columns=['rucksack_1', 'rucksack_2', 'rucksack_3'])

group_rucksack_df['group'] = group_rucksack_df.apply(lambda x: verify_duplicated(x[0], x[1], x[2]), axis=1)

In [116]:
group_rucksack_df['group_prioritie'] = group_rucksack_df.group.map(priorities_dict)

In [117]:
group_rucksack_df.sample(5)

,rucksack_1,rucksack_2,rucksack_3,group,group_prioritie
37,PgTFGPgcBZPcHPFBZRjGPgwCnmwCsmSdQdThmMMMQCQS,JbpvWtvfHblWDHJDzmndSdMQnSwCdhMdQD,rfvWlLlbtfJvvLJpqWbbqZRRGPVFNHVFgZNVFBgH,H,34
61,TTCJhDrmDpRVhvhHfffwzwfz,dmmdmglWcqvHvWsHzB,gdQMZbtlgQlZcMSttCNmVVrLSTTJ,m,13
19,wZccfslqZPFFjrFbFfQQ,vvTvVWCJJZVBWCSvnVJJrhjQVMjVjzbgMQbjpphh,BBmNWBvZRvSqwsGwssPcmc,Z,52
74,jBpCZStjBwWrQCMrhw,TvcHBzHdPPzdvFTzzJlvzdQfThrhhrhfQTWMQfWMqfwf,bzGJJBJcJvdvBPFzddGgjZSbZZngRZNNnnsjRs,B,28
26,cLlrNPvljRhRgTlM,VmDBGnVdmJDnDBndnnVwDRvMgRsTbTzMMsgZghzzsB,SpHvmGnSDJnwvDQqfrCPLpPLCfpF,v,22

In [118]:
answer_part_two = rucksack_df.priorities.sum()


print(f"The answer for the part one is: {answer_part_two}")

The answer for the part one is: 7727